apiVersion: v1
kind: Pod
metadata:
  name: client
spec:
  restartPolicy: OnFailure
  containers:
  - image: registry.cn-hangzhou.aliyuncs.com/amrom/dubbo-go-client:0.0.16
    name: client
    imagePullPolicy: Always
    env:
     - name: NAMESPACE
       valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
     - name: DUBBO_NAMESPACE
       valueFrom:
         fieldRef:
           fieldPath: metadata.namespace
  serviceAccountName: dubbo-sa
